apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: soulseen
    provider: https://github.com
    providerKind: github
    repositories:
    - name: jx-demo
    scheduler: in-repo
